### ISSUE TITLE
Margins for clm (package 'ordinal') models?

### ISSUE THREAD

**Issue by nbreznau** [leeper/margins#137]
The margins package is the bedrock of a large-scale project we are working on. However, we cannot get it to run with cumulative link models (clm from the package 'ordinal'). Perhaps we are not specifying it correctly and need to add a vcov command, but have not figured it out and the margins command returns "'type' is ignored for models of class 'clm'" over and over and over until it eventually aborts and says "cannot allocate vector of size 11.6 Gb"

Any insights would be greatly appreciated, and again thank you so much for this package.

**Comment by leeper** [comment]
Closing into #101
