### ISSUE TITLE
PDF version of intro document

### ISSUE THREAD

**Issue by mlaviolet** [leeper/margins#146]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

I can no longer find the PDF version of "An introduction to 'margins'" online. Could you restore it? Thanks.

**Comment by leeper** [comment]
I don't know what you're referring to. Do you mean? https://cran.r-project.org/web/packages/margins/vignettes/TechnicalDetails.pdf
