### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by leeper** [leeper/margins#16]
- [x] Manual calculation of examples from Matt Golder's [multiplicative interaction terms page](https://files.nyu.edu/mrg217/public/interaction.html)
- [x] Vignette comparing output to output from other packages
  - [x] [car](http://cran.r-project.org/web/packages/car/index.html)
  - [x] [effects](http://cran.r-project.org/web/packages/effects/index.html)
  - [x] [mfx](http://cran.r-project.org/web/packages/mfx/index.html)
  - [x] [erer](http://cran.r-project.org/web/packages/erer/index.html)
  - [x] [visreg](https://cran.r-project.org/web/packages/visreg/index.html)
  - [x] [DAmisc](https://cran.r-project.org/web/packages/DAMisc/index.html)
  - [x] [interplot](http://cran.r-project.org/web/packages/interplot/index.html)
  - [x] [interactionTest](http://cran.r-project.org/web/packages/interactionTest/index.html)
  - [x] [plotMElm](https://github.com/christophergandrud/plotMElm)
- [x] Technical details vignette
- [x] Example showing integration with non-standard variance-covariance matrices from [sandwich](https://cran.r-project.org/web/packages/sandwich/index.html)

**Comment by helix123** [comment]
Is package `effects` also related?

**Comment by leeper** [comment]
Yes, good idea, @helix123. Added it to the list.
