### ISSUE TITLE
Implement fitted values with standard errors and confidence intervals

### ISSUE THREAD

**Issue by mrbrich** [leeper/margins#23]
You state:

> Note: While margins also implements fitted values from model estimation results, that functionality is already well-implemented by R's predict function, so that wheel is not reinvented here.

This is true, but this does not give you standard errors or confidence intervals, which stata's margins command does. So, it would still be nice to have this functionality at some point.

**Comment by leeper** [comment]
@mrbrich It does if you use set `predict(model, se.fit = TRUE)` (which is not the default).

**Comment by mrbrich** [comment]
That is excellent news. What if I follow the example in your vignette:

```{r}
x <- glm(am ~ cyl + hp + wt, data = mtcars, family=binomial)
mean(predict(x, type = "response")) # Probability of success
```

Can I get the SE for the mean of the fitted values?

**Comment by mrbrich** [comment]
This should work:

```{r}
m <- model.matrix(x)
g <- family(x)$mu.eta
h <- (t(m) %*% g(m %*% coef(x)))/nrow(m)
se <- sqrt(drop(t(h) %*% vcov(x) %*% h))
```
