### ISSUE TITLE
Support non-base modelling functions

### ISSUE THREAD

**Issue by leeper** [leeper/margins#3]
- [x] loess
  - `predict()` method uses `se` rather than `se.fit`
- [ ] plm/pglm
  - no `predict()` method
- [x] `MASS::polr()`
  - has `predict()` method with `type = c("class", "probs")`
- [x] `MASS::glm.nb()`
  - should work out of the box
- [ ] lme4 (`lmer()`, `glmer()`, ...)
  - `lme4:::predict.merMod()` has no `se.fit` argument
- [ ] nlme
  - `nlme:::predict.lme()` has no `se.fit` or `type` arguments
  - `nlme:::predict.gls()` has no `se.fit` argument.
- [x] nls
  - requires setting `model = TRUE` in original call; and then getting `term(object[["model"]])`
- [ ] `lfe::felm()`
- [ ] survey
  - (implements alternative modelling functions for non-SRS survey datasets)
- [x] survival
  - coxph class has different `type` values for `predict()`: `c("lp", "risk", "expected")`
  - `survival::survreg()`
- [ ] censReg
  - has a `margEff()` generic but no `predict()` method
- [ ] `nnet::multinom()` or any nnet model generally
- [x] `AER::ivreg()`
- [ ] `quantreg::rq()`
- [x] Document which model types have `prediction()` and `marginal_effects()`/`margins()` methods

**Comment by markdanese** [comment]
This looks like a great package.  Thanks for putting it together.  Thomas Lumley's survey package wraps glm for regression modeling when handling the weights needed for analyzing complex surveys.  I don't know how hard it would be to get that package to work with margins.  (Also, the survival package might be worth considering.)

**Comment by leeper** [comment]
@markdanese Thanks and great suggestions. I've added them to the list.

**Comment by hughjonesd** [comment]
I would throw in a vote for `nnet::multinom`, the multinomial logit. This requires specifying which category of the DV you want to see marginal effects for.

**Comment by leeper** [comment]
@hughjonesd Thanks. I've added it to the list.

**Comment by leeper** [comment]
I am moving this issue here: https://github.com/leeper/prediction/issues/1
