### ISSUE TITLE
Combine efforts from marfx?

### ISSUE THREAD

**Issue by jrnold** [leeper/margins#31]
I'm opening this up to follow-up on our twitter conversation. My package [marfx](https://github.com/jrnold/marfx) replicates some of this package. I don't have time to go into detail  now, but follow up later when I have more time to write my thoughts and how the two packages differ and how we can build on the strengths of each. But in the meantime, I wanted to open up this issue as a place for discussing this.

**Comment by leeper** [comment]
Thanks for starting this. I'll give your package a look once I have a moment and see how easily we can combine.

**Comment by jrnold** [comment]
I need to look back over your package as well. I looked at it prior to writing **marfx** and it was the only package that was good, but I think I had a few different ideas about the API. I'll look again and write up my thoughts.

**Comment by leeper** [comment]
TODO:

- [ ] Optionally use [simulation approach from `marfx`](https://github.com/jrnold/marfx/blob/master/R/methods-lm.R#L20-L33)
- [ ] Expose [internal calculators](https://github.com/leeper/margins/blob/master/R/marginal_effects_internal.R) with better names [a la marfx](https://github.com/jrnold/marfx/blob/master/R/marfx.R#L56-L99)
- [ ] identify "logical" class variables and [handle as factor](https://github.com/leeper/margins/blob/master/R/marginal_effects_methods.R#L26)
- [ ] handle "ordered" class variables as factor
- [ ] Add ggplot2 examples; ensure all output is tidy (it should be, but need to check)
- [ ] Add example data beyond `datasets` (prob. examples from [marfx vignette](https://github.com/jrnold/marfx/blob/master/vignettes/Examples.Rmd))

**Comment by leeper** [comment]
@jrnold I think I've effectively incorporated the core functionality of your package, including the simulation-based variance estimation and the addition of a low-level `dydx()` generic to calculate marginal effects or discrete differences for a single variable in a model. I'm finishing up the vignette explaining the computational approach and when that's done, I plan to push to CRAN. I've credited you as an author, given some of the code is from your package.

**Comment by jrnold** [comment]
Awesome. Sorry I haven't had time to look at it. As I'm prepping/using it for my upcoming classes I'll see what I can add/contribute.
