### ISSUE TITLE
Viewing vignettes

### ISSUE THREAD

**Issue by methodds** [leeper/margins#51]
Hi,

is there currently any way to view the vignettes in a nice format?

Trying ``vignette('Introduction', 'margins')`` results in the warning:
```
Warning message:
vignette ‘Introduction’ has no PDF/HTML 
```

**Comment by leeper** [comment]
If you install without building the vignettes (either using `devtools::install_github()` using the default settings or by manually specifying not to in `ghit::install_github("leeper/margins", build_vignettes = FALSE)`), then you will not have access to the vignettes. The recommended installation procedure `ghit::install_github("leeper/margins")` will give you the vignettes, in HTML format.
