### ISSUE TITLE
Suggestions: Adding more convenience functions/parameters

### ISSUE THREAD

**Issue by methodds** [leeper/margins#52]
Hi,

I'm super happy that one of Stata's biggest strengths will soon be available in R for free. What I would suggest for future versions of the package though is to add some convenience functions/parameters that make it easier to draw more sophisticated graphs without having to write a lot of code.

As an example I imported the [diamonds dataset](https://dl.dropboxusercontent.com/u/22352379/diamonds.csv) from R, created some variables for a logit model and have a lot of trouble replicating the following Stata graph:

````
* Importing the data:
import delimited "diamonds.csv", delimiter(comma) varnames(1) clear 

* Generate dep. variable for logistic regression
recode carat (min/1 = 0 "low") (else= 1 "high"), gen(carat_dummy)

* Generate categorical (factor variable)
gen cut_cat = 1
replace cut_cat = 2 if cut == "Very Good" | cut == "Premium"
replace cut_cat = 3 if cut == "Ideal"

* Generate dummy for color
gen col_g = color == "D"

* Fitting the model
logit carat_dummy i.cut_cat c.price c.depth  i.col_g

* Calculating margins for different depths and only "D" colored diamonds for each cut category
margins, at(depth=(40(5)80) col_g= 1) over(cut_cat)
marginsplot
````

![statamargins_diamonds](https://cloud.githubusercontent.com/assets/7460499/21197962/a4cbdafe-c23d-11e6-9e6e-c2bcecb36578.png)

I assume that it is currently not possible to replicate the outcome of these 2 lines of Stata margins without a large code chunk. It would really be awesome if you could write additional functions/parameters to make this process a little easier.

Anyway, many thanks for putting effort in this project :)

**Comment by leeper** [comment]
I don't think it's much different in R than in Stata. It's a couple of lines of code to do that plot but I wouldn't describe them as particularly complicated.

```R
# load data
library("ggplot2")
data(diamonds)

# clean data
diamonds[["carat_dummy"]] <- ifelse(diamonds[["carat"]] <= 1, 0, 1)
diamonds[["cut_cat"]] <- factor(c("Fair" = 1, "Good" = 1, "Very Good" = 2, "Premium" = 2, "Ideal" = 3)[diamonds[["cut"]]])
diamonds[["col_g"]] <- factor(diamonds[["color"]] == "D")

# estimation
m <- glm(carat_dummy ~ depth + cut_cat + price + col_g, data = diamonds, family = binomial)

# marginal effects
library("margins")
summary(margins(m, at = list(depth = seq(40, 80, by = 5))))

# replicate the plot
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 1, ], col = "blue")
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 2, ], col = "red", draw = "add")
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 3, ], col = "green", draw = "add")
```

Note, though, that Stata extrapolates considerably beyond the supported range of the data. See, for example, `aggregate(depth ~ cut, data = diamonds, FUN = range)`. If you want to do that, you have to specify manual x value ranges for each subplot:

```R
xvals <- prediction::seq_range(diamonds[["depth"]], n = 10)
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 1, ], xvals = xvals, col = "blue", ylim = c(0, 0.4))
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 2, ], xvals = xvals, col = "red", draw = "add")
cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 3, ], xvals = xvals, col = "green", draw = "add")
```

Another option may be to use the `cplot()` function to do relevant calculations, and then dump everything to ggplot2:

```
dat <- do.call(rbind, list(
  cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 1, ], xvals = xvals, draw = FALSE),
  cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 2, ], xvals = xvals, draw = FALSE),
  cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 3, ], xvals = xvals, draw = FALSE)
))
dat[["cut"]] <- factor(rep(1:3, each = 10))
ggplot(dat, aes(x = xvals, y = yvals, colour = cut)) + geom_line() + geom_errorbar(aes(ymin = lower, ymax = upper))
```

So, it's not going to be as simple as just typing `marginsplot` but I would be open to pull requests for code to simplify, for example, the above.

**Comment by methodds** [comment]
Thanks a lot for listing the two options here, this definitely helps me a lot. At the moment I'm still learning how to write + properly document code in R  and would be happy to  think about possible simplifications after that.

There is one thing I don't fully understand about your code though: Why are you using the original dataset as your data source in ``cplot`` and not ```m$model```? Does it make a difference? The predicted probabilites  from your first cplot blocks with and without aggregation look different in comparison to the Stata result:

![diamond_margins_r](https://cloud.githubusercontent.com/assets/7460499/21201688/3cf78ce8-c24c-11e6-86e1-fa539a8cecf3.png)
For example Stata predicts probabilities between 35 and 40% for ``cut_cat2``, while your version never predicts any values above 30%.
The differences remain if I remove the additional condition for ``at col_g= 1`` in the Stata version. I also checked our recoding again and they are identical.

**Comment by leeper** [comment]
Using the model frame rather than the original data can be problematic in lots of cases, which I won't bore you with.

The difference in the plots is that your Stata code uses `over` and there is no analogue to that in my code for R. The over option in essence reestimates the model on subsets of the data. To replicate that, you would need to estimate three `glm()` calls and combine the results from each.

**Comment by methodds** [comment]
I see, thanks for the info. Unfortunately using your described procedure of subsetting the data by a another variable often produces weird results, e.g. estimating educational effects higher for "low" than for "medium" educated people, which contradicts the corresponding model output. If I use code like ``cplot(m, x = "depth", data = diamonds[diamonds[["cut_cat"]] == 1, ])`` from above, what happens to unspecified variables? Are they fixed at their mean or median?

**Comment by leeper** [comment]
Currently they are held at means, but it is my intention to change this to be averaged predictions.

**Comment by leeper** [comment]
@methodds With https://github.com/leeper/prediction/issues/13 now resolved, you may be able to obtain a closer replication of your Stata graph by calling `prediction()` directly and using ggplot2:

```R
library("prediction")
library("ggplot2")
data(diamonds)

# clean data
diamonds[["carat_dummy"]] <- ifelse(diamonds[["carat"]] <= 1, 0, 1)
diamonds[["cut_cat"]] <- factor(c("Fair" = 1, "Good" = 1, "Very Good" = 2, "Premium" = 2, "Ideal" = 3)[diamonds[["cut"]]])
diamonds[["col_g"]] <- factor(diamonds[["color"]] == "D")

# estimation
m <- glm(carat_dummy ~ depth + cut_cat + price + col_g, data = diamonds, family = binomial)

# predicted values (ala `margins`)
p <- prediction(m, at = list(depth = seq_range(diamonds$depth, 9), col_g = "TRUE"))

# plot (ala `marginsplot`)
ggplot(p, aes(x = depth, colour = cut_cat, y = fitted)) +
  stat_summary(fun.data = "mean_cl_normal", geom = "point") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar")
```

![prediction](https://cloud.githubusercontent.com/assets/3505428/24587705/3c3be68e-17b3-11e7-82e8-93f22a98d16c.png)

**Comment by methodds** [comment]
thx for the tip, this is most useful :)
