### ISSUE TITLE
Unable to install margins

### ISSUE THREAD

**Issue by fhollenbach** [leeper/margins#53]
I am trying to install the package on a new mac. MacOS 10.12.2, R version 3.3.2 (2016-10-31). Followed instructions on bottom of page. ghit and leeper/prediction were installed, I get the following error when trying to install margins:
``
install_github("leeper/margins")
Error in build_and_insert(p$pkgname, d, vers, build_args, verbose = verbose) :
  Package build for margins failed!
''

**Comment by leeper** [comment]
Please try again by setting `verbose=TRUE` and copy in the output.

If that doesn't work, you can also try: `devtools::install_github("leeper/margins")`

**Comment by fhollenbach** [comment]
Sorry, should have done that first. 
The package "gapminder" that is required to build the vignette was not installed. Once I installed that first, it worked. Sorry for the unnecessary posting of the issue. 
Thanks for the great package!

**Comment by leeper** [comment]
Okay, great. Thanks.
