### ISSUE TITLE
se for dydx?

### ISSUE THREAD

**Issue by puterleat** [leeper/margins#55]
Apologies if this is already there, but I can't work out how to so the equivalent of:

```
sysuse auto
reg mpg c.price##foreign 
margins, dydx(foreign) at(price=(1000, 5000))
```

Where the resulting table includes a CI for the difference between foreign and domestic at each price. I can see that the following code gives me the SE for the prediction and I could plot if I wanted:

```
m <- lm(mpg~vs*disp, data=mtcars)
prediction(m) %>% 
  bind_cols(find_data(m), .) 
```

However, using dydx doesn't give the SE for the difference, as one might expect:

```
m <- lm(mpg~vs*disp, data=mtcars)
prediction(m) %>% 
  bind_cols(find_data(m), .) 
```

It's also somewhat annoying that the new variable created by dydx is called `vs` which means duplicate variable names when binding with the original dataset. Is it possible to get the SE or CI for the difference?

**Comment by leeper** [comment]
I think you're asking for:

```R
webuse::webuse("auto")
m <- lm(mpg~price*foreign, data = auto)
summary(margins(m, at = list(price = c(1000,5000))))
# $`1000`
# Average Marginal Effects, with price = 1000
# lm(formula = mpg ~ price * foreign, data = auto)
# 
#          Factor   dy/dx Std.Err. z value Pr(>|z|)   2.50%  97.50%
# price     price -0.0010   0.0002 -5.6258   0.0000 -0.0014 -0.0007
# foreign foreign  9.5999   2.5293  3.7955   0.0001  4.6426 14.5573
# 
# $`5000`
# Average Marginal Effects, with price = 5000
# lm(formula = mpg ~ price * foreign, data = auto)
# 
#          Factor   dy/dx Std.Err. z value Pr(>|z|)   2.50%  97.50%
# price     price -0.0010   0.0002 -5.6257   0.0000 -0.0014 -0.0007
# foreign foreign  6.3218   1.2709  4.9742   0.0000  3.8308  8.8127
# 
# Warning message:
# In check_values(data, at) :
#   A 'at' value for 'price' is outside observed data range (3291,15906)!
```

In terms of variable naming, it's on my TODO list to change. All of the marginal effects columns will - probably sometime soon - get a `_` prefix, so the marginal effect of `price` is `_price`. I just haven't gotten to it yet.

**Comment by puterleat** [comment]
OK - thanks, but is that consistent with the Stata behaviour? 

For example,  `margins, at(price=(1000 5000))` wouldn't estimate the dydx of each of the other variables – it would be the predicted mean. To get the same you would have to ask for `margins, dydx(foreign) at(price=(1000 5000))`.  Also, not sure it makes sense to have `price` in the summary table... how would you interpret that -0.0010 figure and intervals etc?

I think I'm generally struggling with the fact that it's hard to extract tidy dataframes from `margins()`.  My instinct is to want to take the estimate and SE and throw them at ggplot. I have spotted that `cplot` returns a dataframe, but it's not that nice an interface to have to call a plotting function to get the data.  I can't immediately see the advantage of margins returning a list — I  find them fiddly to work with — but perhaps it would help to implement a `tidy` which calls summary and then flattens the marginslist to a dataframe?

**Comment by leeper** [comment]
`margins()` emulates:

```Stata
. margins, dydx(*) at(price=(1000, 5000))

Conditional marginal effects                    Number of obs     =         74
Model VCE    : OLS

Expression   : Linear prediction, predict()
dy/dx w.r.t. : price 1.foreign

1._at        : price           =        1000

2._at        : price           =        5000

------------------------------------------------------------------------------
             |            Delta-method
             |      dy/dx   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
price        |
         _at |
          1  |  -.0010159   .0001806    -5.63   0.000    -.0013761   -.0006558
          2  |  -.0010159   .0001806    -5.63   0.000    -.0013761   -.0006558
-------------+----------------------------------------------------------------
1.foreign    |
         _at |
          1  |   9.599944   2.529357     3.80   0.000       4.5553    14.64459
          2  |   6.321767   1.270912     4.97   0.000     3.787013    8.856521
------------------------------------------------------------------------------
Note: dy/dx for factor levels is the discrete change from the base level.

```

rather than:

```Stata
. margins, dydx(foreign) at(price=(1000, 5000))

Conditional marginal effects                    Number of obs     =         74
Model VCE    : OLS

Expression   : Linear prediction, predict()
dy/dx w.r.t. : 1.foreign

1._at        : price           =        1000

2._at        : price           =        5000

------------------------------------------------------------------------------
             |            Delta-method
             |      dy/dx   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
1.foreign    |
         _at |
          1  |   9.599944   2.529357     3.80   0.000       4.5553    14.64459
          2  |   6.321767   1.270912     4.97   0.000     3.787013    8.856521
------------------------------------------------------------------------------
Note: dy/dx for factor levels is the discrete change from the base level.

```

The interpretation of everything in the output is the average marginal effect of the variable. In this example, the AME of `price` is constant across levels of `price` (but that wouldn't necessarily be the case in general; for example if `price` and `price^2` are included, the AME would vary).

Two strategies for tidying:

 - `do.call("rbind.data.frame", margins(m))` will give you a single data frame
 - `cplot()` with `draw = FALSE` will give you the data frame you probably want for plotting with ggplot2. You can think of that as a plotting command, or as a function that generates the data structure you want for purposes of plotting. It does both, optionally.

Another way to get around the list return of `margins()` is to specify a `data` argument. For example, you could basically row-bind two copies of the original data, changing the values of the `at` variables in each. Something like:

```R
d1 <- d2 <- auto
d1$price <- 1000
d2$price <- 5000
margins(m, data = rbind(d1, d2))
```

and then split out the results based on the value of `price`.

**Comment by puterleat** [comment]
Thanks — that makes more sense, although it seems an odd to switch away from the default stata behaviour here. Perhaps I'm too used to Stata, but it seems to make more sense to estimate means rather than differences by default.

On tidying, I can think of various strategies but I wonder if there's perhaps an argument for including an option to bind in the margins call itself, or even making it the default? Stata is wonderful to teach to students because so little code is needed to obtain what is most often wanted. I don't want to teach list processing unless I have to!

**Comment by leeper** [comment]
On the first point, this doesn't estimate means at all - it's not even an option. If you want that, use prediction. Stata using the same command to generate two fundamentally different things is bad behavior, so I'm trying to avoid it here.

**Comment by puterleat** [comment]
> Stata using the same command to generate two fundamentally different things is bad behavior

Ah - OK... I get it now. Apologies for being slow - I think I was misled by the fact there are separate dydx and prediction functions, and I thought your margins was calling (as would Stata).  It might be worth highlighting in the docs that you have elected to split the two roles which the stata `margins` function fulfils – it's not a straight port of stata's `margins` in that sense.

**Comment by leeper** [comment]
Yes, this used to be more explicit in the README, but was edited out at some point. I'll reinstate it.

**Comment by leeper** [comment]
Fixed by https://github.com/leeper/margins/commit/6c7c16140322d2111d1d7ac00a1961b7681f3683
