### ISSUE TITLE
Return additional columns to index margins in tidy dataframe

### ISSUE THREAD

**Issue by puterleat** [leeper/margins#58]
Related to this issue: https://github.com/leeper/prediction/issues/8, I had wondered if you could do something similar with the summary method of margins(). For example, say you had a situation like this:

```
m <- glm(satstill~sticker*lollipop*agemonths, data=dentist, family="binomial")

m.margins <- margins(m, at=list(agemonths=c(50,80,90), lollipop=0:1))
```

It would be nice if summary had the following automatically applied to it, so that it returned a tidy dataframe rather than a list:

```
# new return value for summary.margins
do.call('rbind', lapply(summary(m.margins), 
          function(x) {cbind(attr(x, 'at'), x)})) %>% 
  as_tibble() 
```

I think I might actually find this more useful as a default return from margins itself, but obviously changes the interface which may be annoying.

**Comment by leeper** [comment]
I've been putting some thought on this and I plan to implement it. My current thought is that `margins()` will return a data frame with additional columns, labelled `_at(x1)`, `_at(x2)`, etc. based upon whatever variables are specified in `margins(..., at = list(x1 = ..., x2 = ...))` where the value corresponds to whatever was specified in `at`.

The "marginslist" class and methods will be eliminated. `print.margins()` and `summary.margins()` will gain an `sort` argument specifying how to arrange the output, e.g., `print(margins(..., at = list(x1 = 1:2, x2 = 3:4)), sort = c("x2", "x1")`, etc.

This will be a little challenging because it will require:

 - Changing the `confint.margins()` method
 - Changing the `summary.margins()` method, adding `sort` argument
 - Changing the `print.margins()` method, adding `sort` argument
 - Changing the `plot.margins()` method and deciding how to handle displaying multiple margins
 - Changing the internals of `cplot()`
 - Changing the internals of `persp()`

**Comment by puterleat** [comment]
This is great news... 

Just on the naming convention for the columns though – it can be a real convenience if the names of the columns reflect the model covariates themselves. For example, when plotting it's possible to simply copy and paste plotting code and switch between raw/model-predicted values easily.  An additional thought on this is that, if selecting columns then names like `_at(x1)` would require typing additional backticks to avoid syntax errors.

**Comment by leeper** [comment]
@puterleat Just an update. A nearly finished draft of this is available on the [tidy](https://github.com/leeper/margins/tree/tidy) branch. You can see a code diff here: https://github.com/leeper/margins/compare/tidy?expand=1

I mostly followed your suggestions here, with a few caveats.
 - `margins()` now returns a "data.frame" (always). The number of rows reflects values passed to `at`.
 - The names of the marginal effects columns no longer duplicate the original variables; instead they're prefixed by `dydx_`, which should make them easy to pass to ggplot2, etc.
 - The handling of `at` values turned out to be simpler than I expected. Basically, the returned data frame will contain the *modified* values of the original data, so you can just use the original column names to subset or plot by anything you want the AMEs *at*. If you want the *original* values of those variables, you'll have to bind them back to the output of `margins()`. There's no way to do this nicely without repeating column names in a weird way.
 - There's also a new `.at` column, which is actually a list of variable-named values at which the data have been modified. (Working with that column is probably weird but you shouldn't need to access it directly. It's used within `print.margins()` and `summary.margins()` to handle printing.)

Behavior is pretty straightforward and hopefully intuitive:

```R
x <- lm(mpg ~ cyl * hp + wt, data = mtcars)
marg1 <- margins(x)
summary(marg1)

marg2 <- margins(x, at = list(hp = c(150, 300), cyl = c(4,6)))
summary(marg2)
```

This isn't yet on the master branch, but it seems to be passing tests. It's a breaking change to package API, though, so any existing code probably won't work as expected any more.

**Comment by puterleat** [comment]
This is all really great stuff... I particularly like the idea of always returning a data frame.
I'm not sure I fully understand what _is_ being returned at the moment though. For example, when I run the following the output doesn't make sense to me:

```
#install
install.packages('devtools')
devtools::install_github('leeper/margins', ref="78088387e997a14cd867892e588f497f9810912e")
library(margins)
library(dplyr)

```

then 

```
> x <- lm(mpg ~ cyl * hp + wt, data = mtcars)
> marg2 <- margins(x, at = list(hp = c(150, 300), cyl = c(4,6)))
> marg2
             .at    cyl       hp    wt
 hp: 150, cyl: 4 0.1009 -0.08778 -3.12
 hp: 150, cyl: 6 0.1009 -0.04987 -3.12
 hp: 300, cyl: 4 2.9440 -0.08778 -3.12
 hp: 300, cyl: 6 2.9440 -0.04987 -3.12
```

This looks like a data frame, but not with all the columns I'd expect (e.g. where is the SE?). Moreover:

```
> marg2 %>% names
 [1] "mpg"          "cyl"          "disp"         "hp"           "drat"        
 [6] "wt"           "qsec"         "vs"           "am"           "gear"        
[11] "carb"         "fitted"       "se.fitted"    "dydx_cyl"     "dydx_hp"     
[16] "dydx_wt"      "Var_dydx_cyl" "Var_dydx_hp"  "Var_dydx_wt"  ".at"         

> marg2[1,]
             .at    cyl       hp    wt
 hp: 150, cyl: 4 0.1009 -0.08778 -3.12
> 
```


I think my confusion is that I'm assuming that if you called margins with just a list for `at()` , I would expect that this list is expanded (e.g. with `expand.grid` in base), and then passed to the prediction or dydx function as appropriate, but this is not what is occurring?  The interface/API seems to be somewhere between what you would expect from an R `fitted` or `predict` function, and the actual Stata `margins` command.

So, for example in Stata you do this:

```
sys use auto
reg mpg c.price##c.weight

. margins, at(weight=(1000 2000) price=(3000 4000) )
Adjusted predictions                            Number of obs     =         74
Model VCE    : OLS

Expression   : Linear prediction, predict()

1._at        : price           =        3000
               weight          =        1000

2._at        : price           =        3000
               weight          =        2000

3._at        : price           =        4000
               weight          =        1000

4._at        : price           =        4000
               weight          =        2000

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
         _at |
          1  |   37.63801   1.710284    22.01   0.000     34.22696    41.04907
          2  |    29.9659   .9975961    30.04   0.000     27.97625    31.95554
          3  |   35.89476   1.373245    26.14   0.000     33.15591    38.63361
          4  |   28.83639   .7632115    37.78   0.000     27.31421    30.35856
------------------------------------------------------------------------------
```


In R I would expect a function that tried to replicate the functionality to do something like this:

```
m <- lm(mpg~price*weight, data=auto)
forthesevalues = expand.grid( weight = c(1000, 2000), price = c(3000,4000))
marg1 <- margins(m, at=forthesevalues)

marg1

  weight price fitted se t p lower upper
1   1000  3000      X  X X X     X     X
2   2000  3000      X  X X X     X     X
3   1000  4000      X  X X X     X     X
4   2000  4000      X  X X X     X     X
```

Note, if you passed a list to the `at` parameter then the grid expansion would happen automatically.

For the case of `dydx` in Stata you might say:

```
reg mpg i.foreign##c.price##c.weight
margins, dydx( foreign) at(weight=(1000 2000) price=(3000 4000) )
```

Which produces:

```
Conditional marginal effects                    Number of obs     =         74
Model VCE    : OLS

Expression   : Linear prediction, predict()
dy/dx w.r.t. : 1.foreign

1._at        : price           =        3000
               weight          =        1000

2._at        : price           =        3000
               weight          =        2000

3._at        : price           =        4000
               weight          =        1000

4._at        : price           =        4000
               weight          =        2000

------------------------------------------------------------------------------
             |            Delta-method
             |      dy/dx   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
1.foreign    |
         _at |
          1  |   5.379087   5.465928     0.98   0.329     -5.53399    16.29217
          2  |   .7547027   2.251945     0.34   0.739     -3.74145    5.250856
          3  |    4.65199   4.892753     0.95   0.345    -5.116707    14.42069
          4  |   .4205528   1.606517     0.26   0.794    -2.786962    3.628068
------------------------------------------------------------------------------
Note: dy/dx for factor levels is the discrete change from the base level.
```

So to replicate this in R, you might either pass a boolean or "all" to get the marginal effect of all terms (which is the default you have now I think), or pass a string or list to get just one or more (which is what Stata would expect):

```
m <- lm(mpg~foreign+weight+price, data=auto)
marg2 <- margins(m, dydx="all", at=forthesevalues)
head(marg2)

  weight price dydx_foreign se t p lower upper
1   1000  3000            X  X X X     X     X
2   2000  3000            X  X X X     X     X
3   1000  4000            X  X X X     X     X
4   2000  4000            X  X X X     X     X
```

Stata behaves weirdly by allowing factor variables to be listed in the varlist after the margins command. One could obviously require people to use the `at` syntax to specify the categories they want estimates for explicitly:

```
forthesevalues = expand.grid(
  weight = c(1000, 2000), 
  price = c(3000,4000), 
  foreign=unique(auto$foreign)
)
marg3 <- margins(m, at=forthesevalues)
```

Or alternatively perhaps allow factors to be specified as unquoted variable names in the margins call itself perhaps in the same way as dplyr::select does:

```
margins(m, foreign, at = ...) 
```

Or as another string or character vector:

```
margins(m, factors="foreign", at = ...) 
or 
margins(m, factors=c("foreign", "anotherfactor"), at = ...) 
```

Which would effectively just add all the factor levels for `foreign` to the list to be expanded. This is a little bit magic, but is probably reasonably intuitive, and would certainly be what someone coming from Stata would expect.

Finally, just on the idea of including an additional column called `.at`. I wonder if this would be better places as an attribute/property on the dataframe returned rather than merged into the estimates themselves?

Apologies for such a long comment, and I hope this does't feel like criticism of the excellent work you've done. I think this margins library will be such an excellent companion when modelling in R it's really worth the effort to think through the API now and make it as consistent and intuitive as possible, because it can then serve as a simple wrapper to the various backends needed for different types of models. For example, `brms` has implemented some similar functionality for bayesian models fit in Stan, but like all these things, the interface is subtly different and it would be lovely if the margins package could become the default to use for all model types, and which hides the inconsistencies across R packages.

It may be that I'm ignoring important use-cases of margins which would be hard to accommodate this way, but it feels like you have all the machinery to make this work with very little friction now, and it's mostly just how the results are output that is to be optimised?

**Comment by leeper** [comment]
I don't have time to respond to all of that, but I suspect the main thing is that to match Stata's output, you want to use the `summary()` method, like: `summary(margins(model))`.

- `margins()` returns a data frame of the raw (possibly modified by `at`) data with columns for unit-specific marginal effects, variances thereof, etc. (note: this has a `print()` method that is just a glance at the resulting marginal effects - the basic print output doesn't really reflect the structure of the `"margins"`-class object - think like print method for `lm()`).
- `summary(margins())` returns a data frame of the *average* marginal effect of each term for each combination of `at` values (it will look close to identical to Stata's output)

I think it most cases you want to work with the output of the `summary()` method.

**Comment by puterleat** [comment]
Ah yes, having looked at summary that makes more sense, thanks. I think then that what I say above applies more to the output of the summary function rather than the main return value... In particular that the `.at` column in that output would be better replaced by multiple columns, one for each variable listed in the `at` list, and giving the value of the covariate at which the margin was calculated, to make plotting this summary data_frame  using ggplot easier.

In general, I think I'm probably coming at this from a different use-case and perhaps therefore don't see the point of this full data_frame in which the marginal effects are in effect repeated down the rows with common x values. I suppose this would be useful if you wanted to do calculations equivalent to Stata's `within` or `over` options, but my suspicion is that this full data_frame is actually more of an implementation detail for most users, and not the thing of primary interest. I don't actually know one would obtain the data_frame that is currently returned by default  when using Stata. What would I want to use it for, as opposed to  the data_frame obtained with `summary(marg1)`?

**Comment by leeper** [comment]
Yes, that's a great idea. I was thinking about returning multiple columns instead of the current single column; the current setup reflects migrating old code but that's where I'd like to head before pushing this to the master branch (and to CRAN).

There are definitely use cases for the raw information (e.g., plotting) and espeically if you're thinking about models other than OLS where the (response-scale) marginal effect (and its variance) would necessarily differ for each unit due to the nonlinear link transformation. (You can get this information in Stata by doing some of the wonky predict/save-as-new-variables options.)

**Comment by puterleat** [comment]
Ah nice... If you do revise the code for the data_frame that is returned you might also want to consider the column names — it's much easier for others to handle simple names without spaces, special chars etc, and then output those in the print functions. e.g. "Pr(>|z|)" should probably just be "p" as a column name.

On the unit-marginal effects, thanks for the hint - I was mainly thinking in terms of continuous response models. However, it might well be worth thinking about whether this is the default — given how fiddly they are to compute in Stata, I can't imagine they are currently often used, and the df produced by summary would be much more frequently in demand, and so a more intuitive default?

**Comment by leeper** [comment]
@puterleat Thanks for the suggestion on column names. I've simplified them as you suggest.

In terms of default, I think it makes sense to leave it as it is. If most people want the summary structure, it's not that hard to wrap it in `summary()`.

I've merged these changes into master and will release to CRAN soon.
