### ISSUE TITLE
Margins for ivprobit models

### ISSUE THREAD

**Issue by rogorido** [leeper/margins#70]
First of all, thanks a lot for your very useful package. Is there any chance that you also support the object ivprobit created by the package ivprobit (https://cran.r-project.org/package=ivprobit)? The package is horribly documented (it is not documented at all) and as far as I can see the code does not follow usual model specifications: https://github.com/cran/ivprobit/blob/master/R/ivprobit.R . 

In case you do not want to support this type of model, could you give me maybe a tip how I could improve the code of ivprobit to make it work with margins?

**Comment by leeper** [comment]
Thanks. I will consider it. The package does not look like it is being actively maintained, though, so I'm a bit hesitant to support it. Supporting new methods is fairly straightforward if they produce model objects that look something like `"glm"` and have a `predict()` method. If they lack the latter, there's currently no way to make them work in this framework.

**Comment by rogorido** [comment]
Thanks for your answer. I wrote to the author, but I'm not very confident that he will answer. In any case, I could at least for me make some experiments. I see that `glm` objects have a list with a lot of elements. Exactly which elements would be strictly necessary to plug in the model to `margins()`?

**Comment by leeper** [comment]
It needs to be able to produce a `predict()` method. This typically requires data and a `"terms "` object of some kind; though different packages implement this in various ways. Ultimately, margins is just a numerical derivative tool, so it needs to be able to get a vector of predicted values from a data frame of input data (i.e., what `predict()` does).

**Comment by rogorido** [comment]
Thanks. I will give it a try.

**Comment by leeper** [comment]
Consolidating this to: https://github.com/leeper/margins/issues/101
