### ISSUE TITLE
margins() fails when design matrix is rank deficient

### ISSUE THREAD

**Issue by leeper** [leeper/margins#71]
Reproducible example:

```R
mtcars$wt2 <- mtcars$wt
m <- lm(mpg ~ wt + wt2, data = mtcars)
m
## 
## Call:
## lm(formula = mpg ~ wt + wt2, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt          wt2  
##      37.285       -5.344           NA
prediction(m)
## Average prediction for 32 observations: 20.0906
## Warning message:
## In predict.lm(model, newdata = out[[i]], type = type, se.fit = TRUE,  :
##   prediction from a rank-deficient fit may be misleading
margins(m)
## Error in jacobian %*% vcov : non-conformable arguments
## In addition: There were 20 warnings (use warnings() to see them)
```

This can occur when some factor levels are colinear. Presumably the solution is either to fail with a more informative error, or to recognize what terms are being dropped from the model and not attempt to estimate the marginal effects thereof.

**Comment by hbahamonde** [comment]
I get this error when estimating a model with **interactions** and **lags**, using the ``plm`` package. 

Error:
``Error in crossprod(beta, t(X)) : non-conformable arguments``.

**Comment by leeper** [comment]
Closing this for now as I think the issue is fixed for lm/glm. {plm} remains an ongoing source of frustration, which I'll need to resolve separately.

**Comment by sanseveroj** [comment]
Hi I was just wondering if the plm package issues got resolved as I am experiencing this issue.

**Comment by leeper** [comment]
No, unfortunately not

**Comment by Shandu99** [comment]
Hi! I was wondering if this issue has been checked on glm.nb from MASS package, because I am experiencing it
