### ISSUE TITLE
Functionality of margins for felm objects

### ISSUE THREAD

**Issue by janpierskalla** [leeper/margins#73]
Hi there,

Thanks so much for creating this awesome package! I was wondering if there is a chance to extend the functionality of margins to cover felm objects produced by the lfe package (https://cran.r-project.org/web/packages/lfe/index.html). The lfe package implements the estimation of fixed effects models in R and is incredibly useful. felm objects currently do not work with margins. AFAIK, the lfe package does not come with a predict function but some users have created a workaround: https://github.com/skranz/regtools/blob/master/R/felm.r

Thanks for considering!

Best,
Jan

**Comment by leeper** [comment]
So, I'm looking into this more. Unfortunately there is no `predict()` method in lfe (and I can imagine it would be hard to build one that covers all functionality possible in the package) and that "regtools" package is not on CRAN (and [a different package with the same name](https://cran.r-project.org/package=regtools) is already on CRAN so it will never be there in its current form). Finally, the license on that code is GPL, so I can't incorporate the code directly here. I'll revisit again in the future.

**Comment by leeper** [comment]
Consolidating this to: https://github.com/leeper/margins/issues/101

**Comment by DeFilippis** [comment]
Has there been any update to this since last year?  I have a model that requires fixed effects and clustering of standard errors -- was hoping to use the margins package on this.
