### ISSUE TITLE
average marginal effects for subset of variables

### ISSUE THREAD

**Issue by jepusto** [leeper/margins#74]
Is there a convenient way to calculate an average marginal effect for a user-specified set of terms, along with an SE and CI? I see that `dydx()` will provide the unit-specific derivatives, but it appears that only margins()` provides the SE and CI. 

The use-case I have in mind is calculating a marginal odds ratio or risk ratio for a treatment indicator in a logistic regression model, as in:
```
library(margins)

n <- 10000
Trt <- c(rep(0, n / 2), rep(1, n / 2))
Z <- rnorm(n)
M_pr <- 1 / (1 + exp(-(Trt + 0.7 * Z - 2)))
M <- rbinom(n, size = 1, prob = M_pr)

T_fit <- glm(M ~ Trt, family = binomial())
summary(T_fit)
summary(margins(T_fit))

Z_fit <- glm(M ~ Trt + Z, family = binomial())
summary(Z_fit)
summary(margins(Z_fit))
```

Is there a way to skip calculating the marginal effects for Z?

(This might be out of scope for the package, I realize.)

**Comment by leeper** [comment]
If you don't care about the variances of the marginal effects, you can use `marginal_effects()` directly and specify the `variables` argument. This will only calculate the vector of marginal effects of the specified variables. Unfortunately calculating variances (as is `margins()`'s default behavior) requires the full variance-covariance matrix so there's no (efficient) way to just get estimates for a subset of variables (that I am aware of).

**Comment by leeper** [comment]
I realized I never followed up on this, but you can now also use the `variables` argument in `margins()`:

```R
n <- 10000
Trt <- c(rep(0, n / 2), rep(1, n / 2))
Z <- rnorm(n)
M_pr <- 1 / (1 + exp(-(Trt + 0.7 * Z - 2)))
M <- rbinom(n, size = 1, prob = M_pr)

T_fit <- glm(M ~ Trt, family = binomial())
summary(margins(T_fit, variables = "Trt"))
##  factor    AME     SE       z      p  lower  upper
##     Trt 0.1515 0.0081 18.6961 0.0000 0.1357 0.1674

Z_fit <- glm(M ~ Trt + Z, family = binomial())
summary(margins(Z_fit, variables = "Trt"))
##  factor    AME     SE       z      p  lower  upper
##     Trt 0.1501 0.0077 19.5122 0.0000 0.1351 0.1652
```

**Comment by jepusto** [comment]
This is great! Thanks Thomas!
