### ISSUE TITLE
Stargazer

### ISSUE THREAD

**Issue by androdri1** [leeper/margins#75]
Sorry for the question, but, is there a simple way to use margins with stargazer? I'm trying to present the marginal effects of three different models. Kind of using "margins , post" and then "esttab" in Stata

My first guess was as follows, but was terribly unsuccessful

```R
a=summary(margins(LPM ))    # This is at the mean  
b=summary(margins(probit ))    # This is at the mean  
c=summary(margins(logit ))    # This is at the mean 

stargazer( a,b,c, type="text") 
```

**Comment by leeper** [comment]
As far as I know, there is no way to make this work with stargazer. You'd have to ask the maintainer of that package to add support.
