### ISSUE TITLE
Plots fail with margins applied using an `at` specification that modifies only one variable

### ISSUE THREAD

**Issue by cyberbryce** [leeper/margins#78]
Reproducible example (R 3.4.2, margins 0.3.0) in which margins and a plot are requested after the `mtcars` regression from the documentation, using an `at` specification modifying only the variable `hp`:

```
require(margins)
require(datasets)
fit2 <- lm(mpg ~ cyl * hp + wt, data = mtcars)
marg2 <- margins(fit2, at = list(hp = c(150, 300)))
summary(marg2)
plot(marg2)
```

The fix is to change line 7 of `plot.margins` to extract columns while setting `drop = FALSE`, so that `at_levels` is always an object of dimension greater than 1, and hence `n_at_levels` is always a scalar. Alternatively, change line 8 to use `NROW` instead of `nrow`. Either change won't affect anything but to ensure the correctness of `n_at_levels` because `at_levels` isn't used anywhere else.

**Comment by leeper** [comment]
Thanks. This should now be fixed.

![example](https://user-images.githubusercontent.com/3505428/35410385-2f468e12-020d-11e8-9a6c-0fa3a26b1d34.png)
