### ISSUE TITLE
cplot() behavior when plotting outside observed data points

### ISSUE THREAD

**Issue by jwbenning** [leeper/margins#88]
This may betray some statistical ignorance, but here goes:

Using a reproducible example:
```
x <- glm(Sepal.Length ~ stats::poly(Sepal.Width, 3), data = iris)
cplot(x, "Sepal.Width")
```
gives
![image](https://user-images.githubusercontent.com/31042228/36033677-593f224a-0d77-11e8-94f7-c3f3290b0797.png)

Say I want to look beyond the limits of the observed data, so I run:
```
cplot(x, "Sepal.Width", xvals = seq_range(c(0,5), 40), xlim = c(0,5))
```
I get:
![image](https://user-images.githubusercontent.com/31042228/36033739-7731a7b4-0d77-11e8-939d-1ecba2cea825.png)

Why, for the same Sepal.Width, say, 2, would merely increasing the range of data values change the predictions so much (i.e., from 4.9 to 6.3)? Shouldn't the predictions for a given xval stay the same? Or am I totally missing something?

**Comment by leeper** [comment]
Looks like an axis bug. I'll investigate.

**Comment by leeper** [comment]
Some debugging reveals this is a result of how `poly()` is handled by `predict()`. I'll need to do more work, but a demonstration of why that's the source is as follows:

```R
x <- glm(Sepal.Length ~ Sepal.Width + I(Sepal.Width^2) + I(Sepal.Width^3), data = iris)
cplot(x, "Sepal.Width", xlim = c(0,5), ylim = c(0,10))
```
![plot1](https://user-images.githubusercontent.com/3505428/36158712-def1b4ce-10d4-11e8-8d5c-fc0ce0f93eb3.png)



```R
cplot(x, "Sepal.Width", xvals = seq_range(c(0,5), 40), xlim = c(0,5), ylim = c(0,10))
```

![plot2](https://user-images.githubusercontent.com/3505428/36158721-e2acbd98-10d4-11e8-8a73-f7240f14dd86.png)

As that shows, the problem does not occur when specifying an equivalent model without `poly()`. The underlying issue therefore needs to be addressed in how `predict()` and `prediction::prediction()` deal with this. Opening a related issue about it here: https://github.com/leeper/prediction/issues/22

**Comment by leeper** [comment]
I'm guessing this is in fact due to the big discussed here: https://stat.ethz.ch/pipermail/r-devel/2018-April/075889.html

**Comment by jwbenning** [comment]
ah I see. good to be aware of!

**Comment by leeper** [comment]
And that issue has now been patched [in R-devel](https://github.com/wch/r-source/commit/e372854d6bc45cf6ce8d87ae67eca83f341c09a4).

I now get the following plots for your example code:

```R
x <- glm(Sepal.Length ~ stats::poly(Sepal.Width, 3), data = iris)
cplot(x, "Sepal.Width")
```

![cplot1](https://user-images.githubusercontent.com/3505428/39872798-fd6ce3f4-5460-11e8-9a20-c88b8e160152.png)

```R
cplot(x, "Sepal.Width", xvals = seq_range(c(0,5), 40), xlim = c(0,5))
```

![cplot2](https://user-images.githubusercontent.com/3505428/39872802-ff688406-5460-11e8-8f1d-f636583f89c5.png)

That seems to be what we would expect, so I'm closing this. Thanks for reporting it!

```R
> sessionInfo()
R Under development (unstable) (2018-05-05 r74699)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] prediction_0.3.2 margins_0.3.21  

loaded via a namespace (and not attached):
[1] MASS_7.3-50       compiler_3.6.0    tools_3.6.0       data.table_1.10.5
```

**Comment by leeper** [comment]
Just a note that an update to prediction v0.3.5 will also eliminate the need for the `stats::` prefix on `poly()`.
