### ISSUE TITLE
Adding margins for GEE

### ISSUE THREAD

**Issue by ClaireRN** [leeper/margins#96]
I'm writing about a suggested feature.

I've been switching back and forth between R and Stata because I need to use margins after I run GEE and that does not work with this package. However, now I need to weight my GEE regression for response propensity since my other planned methods (mice) did not work well. I'm told the weighting for GEE in stata does not work, so now I need to come back to R.  It'd be great to be able to use margins with my GEE object (I'm using geesepack).

**Comment by leeper** [comment]
Thanks. geepack doesn't have `predict()` methods for any of its common modelling functions so it's so far not supportable. `gee::gee()` should be supportable, though.

**Comment by leeper** [comment]
Consolidating this to: https://github.com/leeper/margins/issues/101
