### ISSUE TITLE
Margins for clustered standard errors - lm.cluster

### ISSUE THREAD

**Issue by jaySf** [leeper/margins#97]
Thanks for providing **margins**  since it's invaluable for statistical analysis with non-proprietary software!

We are looking for a way to compute marginal effects with clustered standard errors which seems not yet to be possible with R. I found out that `miceadds::lm.cluster()` computes the same clustered standard errors as Stata. It also provides a `predict()` method.

```
library(ggplot2)
data(diamonds)

# install.packages("miceadds")
library(miceadds)

fit_cl <- lm.cluster(price ~ carat + cut, data = diamonds, cluster="cut")
```
`str(fit_cl)` shows us that the `lm.cluster` object consists of a list with `names(fit_cl)`:

```
> names(fit_cl)
[1] "lm_res" "vcov" 
``` 
Applying `margins::margins(fit_cl[[1]])` yields a result, but with normal standard errors. The clustered ones apparently are stored in the `vcov` in second object of the list. 

`predict(fit_cl[[1]])` is already working, so it seems to be promising to easily implement a method for `lm.cluster` in order to be able to compute marginal effects with clustered standard errors in R.

**Comment by leeper** [comment]
If you have a variance-covariance matrix that you want to use, you can pass it to `margins(..., vcov = your_matrix)`. There's an example of this (for heteroskedasticity-consistent SEs) in `? margins`. You can adapt the code for any arbitrary variance-covariance matrix.

**Comment by jaySf** [comment]
Thank you so much for clarifying this, works like a charm and yields the same AME as Stata!
