### ISSUE TITLE
marginal effect for nnet's multinom does not report SE, z, p, etc.

### ISSUE THREAD

**Issue by eijoac** [leeper/margins#98]
```
summary(margins(model_multi))
```
`model_multi` is a multinomial logistic regression model defined by nnet's multinom. The marginal effect report shows AME, but for SE, z, p, lower, upper, all values are `NA`.

**Comment by leeper** [comment]
Thanks. Will try to get this supported.

**Comment by leeper** [comment]
This is a work in progress. I'm consolidating my tracking of new model support to this issue: https://github.com/leeper/margins/issues/101. Please follow along there.
